version: "3.7"
services:
        dev:
                container_name: dev
                build:
                        context: .
                        dockerfile: Dockerfile
                env_file: .env.development
                command: sh -c "python manage.py runserver 0:9000"
                volumes:
                        - .:/townonewheel/
                ports:
                        - "9000:9000"


        nginx:
               image: nginx:latest
               container_name: nginx_production
               ports:
                       - "80:80"
               volumes:
                       - .:/townonewheel
                       - ./config/nginx/:/etc/nginx/conf.d
                       - ./static:/static
               depends_on:
                       - prod

        prod:
               container_name: django-production
               build:
                       context: .
                       dockerfile: Dockerfile
               env_file: ./config/.env
               command: sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
               volumes:
                       - .:/townonewheel/
               ports:
                       - "8000:8000"
