# Generated by Django 3.2.4 on 2021-06-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(blank=True, choices=[('GRAY', '회색'), ('YELLOW', '노란색'), ('BLACK', '검은색'), ('WHITE', '하얀색')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', '암컷'), ('DONT_KNOW', '모름'), ('MALE', '수컷')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='neutering',
            field=models.CharField(blank=True, choices=[('DONT_KNOW', '모름'), ('O', 'O'), ('X', 'X')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='catimage',
            name='url',
            field=models.TextField(),
        ),
    ]
