# Generated by Django 3.2.4 on 2021-06-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210629_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='cat_like',
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(blank=True, choices=[('GRAY', '회색'), ('BLACK', '검은색'), ('YELLOW', '노란색'), ('WHITE', '하얀색')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(blank=True, choices=[('DONT_KNOW', '모름'), ('MALE', '수컷'), ('FEMALE', '암컷')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='catimage',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
