# Generated by Django 3.2.4 on 2021-06-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210629_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', '하얀색'), ('BLACK', '검은색'), ('YELLOW', '노란색'), ('GRAY', '회색')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', '암컷'), ('DONT_KNOW', '모름'), ('MALE', '수컷')], max_length=20, null=True),
        ),
    ]
