# Generated by Django 3.2.4 on 2021-07-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20210629_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', '하얀색'), ('GRAY', '회색'), ('YELLOW', '노란색'), ('BLACK', '검은색')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(blank=True, choices=[('DONT_KNOW', '모름'), ('FEMALE', '암컷'), ('MALE', '수컷')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='neutering',
            field=models.CharField(blank=True, choices=[('DONT_KNOW', '모름'), ('O', 'O'), ('X', 'X')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='catimage',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
