# Generated by Django 3.2.4 on 2021-07-01 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210629_0610'),
        ('crud', '0006_auto_20210701_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='upload_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload', to='social.profile'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', '하얀색'), ('GRAY', '회색'), ('BLACK', '검은색'), ('YELLOW', '노란색')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', '수컷'), ('DONT_KNOW', '모름'), ('FEMALE', '암컷')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='neutering',
            field=models.CharField(blank=True, choices=[('O', 'O'), ('DONT_KNOW', '모름'), ('X', 'X')], max_length=10, null=True),
        ),
    ]
