# Generated by Django 3.2.4 on 2021-07-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20210701_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='location_lat',
            field=models.FloatField(default=33.450705),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='location_lon',
            field=models.FloatField(default=126.570677),
            preserve_default=False,
        ),
    ]
