# Generated by Django 3.2.4 on 2021-07-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20210701_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='location',
            field=models.TextField(default=True),
        ),
    ]
