# Generated by Django 3.2.4 on 2021-07-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_auto_20210705_2353'),
        ('crud', '0012_auto_20210705_0821'),
    ]

    operations = [
    ]
