# Generated by Django 3.2.4 on 2021-07-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_auto_20210706_0807'),
        ('crud', '0014_auto_20210707_0930'),
    ]

    operations = [
    ]
