# Generated by Django 3.2.4 on 2021-07-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_merge_0014_auto_20210706_0807_0014_auto_20210707_0930'),
        ('crud', '0015_merge_20210708_0315'),
    ]

    operations = [
    ]
