# Generated by Django 3.2.4 on 2021-07-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_auto_20210714_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='created_at',
            field=models.TextField(default=1626341106.4797702),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1626341106.4797702),
        ),
    ]
