# Generated by Django 3.2.4 on 2021-07-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0024_auto_20210721_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='created_at',
            field=models.TextField(default=1626862528.142807),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1626862528.142807),
        ),
    ]
