# Generated by Django 3.2.4 on 2021-07-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_auto_20210716_0920'),
        ('crud', '0023_auto_20210715_0850'),
        ('crud', '0025_auto_20210721_1015'),
    ]

    operations = [
    ]
