# Generated by Django 3.2.4 on 2021-07-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_auto_20210707_0930'),
        ('social', '0004_auto_20210704_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='favorite_cat',
            field=models.ManyToManyField(related_name='catrelationship', to='crud.Cat'),
        ),
    ]
