# Generated by Django 3.2.4 on 2021-07-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_auto_20210713_0112'),
        ('social', '0005_relationship_favorite_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.TextField(default=1626138764.3394933),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='favorite_cat',
            field=models.ManyToManyField(blank=True, related_name='catrelationship', to='crud.Cat'),
        ),
    ]
