# Generated by Django 3.2.4 on 2021-07-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20210713_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
