# Generated by Django 3.2.4 on 2021-07-26 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0012_alter_relationship_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
